create table if not exists public.daily_strawberries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  reward_date date not null,
  created_at timestamptz not null default now(),
  unique (user_id, reward_date)
);

alter table public.daily_strawberries enable row level security;

drop policy if exists "users can read own strawberries" on public.daily_strawberries;
create policy "users can read own strawberries"
on public.daily_strawberries for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "users can insert own strawberries" on public.daily_strawberries;
create policy "users can insert own strawberries"
on public.daily_strawberries for insert
to authenticated
with check (auth.uid() = user_id);

create or replace function public.claim_daily_strawberry(
  p_reward_date date,
  p_start timestamptz,
  p_end timestamptz
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_id bigint;
begin
  if v_user_id is null then
    return false;
  end if;

  if not exists (
    select 1
    from public.task_completions
    where user_id = v_user_id
      and completed_at >= p_start
      and completed_at < p_end
  ) then
    return false;
  end if;

  insert into public.daily_strawberries (user_id, reward_date)
  values (v_user_id, p_reward_date)
  on conflict (user_id, reward_date) do nothing
  returning id into v_id;

  return v_id is not null;
end;
$$;

grant execute on function public.claim_daily_strawberry(date, timestamptz, timestamptz) to authenticated;
