create table if not exists public.daily_checkins (
  user_id uuid not null references auth.users(id) on delete cascade,
  checkin_date date not null default current_date,
  created_at timestamptz not null default now(),
  primary key (user_id, checkin_date)
);

create table if not exists public.task_completions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  task text not null,
  completed_at timestamptz not null default now()
);

create index if not exists task_completions_user_completed_idx
  on public.task_completions(user_id, completed_at desc);

alter table public.daily_checkins enable row level security;
alter table public.task_completions enable row level security;

create policy "users can read own daily checkins"
  on public.daily_checkins for select
  using (auth.uid() = user_id);

create policy "users can insert own daily checkins"
  on public.daily_checkins for insert
  with check (auth.uid() = user_id);

create policy "users can read own task completions"
  on public.task_completions for select
  using (auth.uid() = user_id);

create policy "users can insert own task completions"
  on public.task_completions for insert
  with check (auth.uid() = user_id);
