-- Shared room strawberries: seed each active room with a few berries and
-- drop more when someone completes a task. Picking is server-authoritative.

begin;

create table if not exists public.room_strawberries (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references public.rooms(id) on delete cascade,
  x_percent smallint not null check (x_percent between 8 and 88),
  y_percent smallint not null check (y_percent between 12 and 82),
  source text not null check (source in ('entry', 'completion')),
  spawned_at timestamptz not null default now(),
  claimed_by uuid references auth.users(id) on delete set null,
  claimed_at timestamptz
);

create index if not exists room_strawberries_room_unclaimed_idx
  on public.room_strawberries(room_id, spawned_at)
  where claimed_by is null;

create table if not exists public.strawberry_pickups (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  room_strawberry_id uuid not null references public.room_strawberries(id) on delete cascade,
  picked_at timestamptz not null default now(),
  unique (room_strawberry_id)
);

create index if not exists strawberry_pickups_user_idx
  on public.strawberry_pickups(user_id, picked_at desc);

alter table public.room_strawberries enable row level security;
alter table public.strawberry_pickups enable row level security;

revoke all on table public.room_strawberries from anon, authenticated;
revoke all on table public.strawberry_pickups from anon, authenticated;
grant select on table public.room_strawberries to authenticated;
grant select on table public.strawberry_pickups to authenticated;

-- Users may only see berries from the room they are actively in.
drop policy if exists "active room members can read strawberries" on public.room_strawberries;
create policy "active room members can read strawberries"
  on public.room_strawberries for select
  to authenticated
  using (
    exists (
      select 1
      from public.room_sessions rs
      where rs.user_id = auth.uid()
        and rs.room_id = room_strawberries.room_id
        and rs.expires_at > now()
        and rs.status <> 'done'
    )
  );

drop policy if exists "users can read own strawberry pickups" on public.strawberry_pickups;
create policy "users can read own strawberry pickups"
  on public.strawberry_pickups for select
  to authenticated
  using (user_id = auth.uid());

-- Seed 1-5 berries once per room per Taipei calendar day. The first active
-- member entering that day performs the seed under a room/day advisory lock.
create or replace function public.ensure_room_strawberries()
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_room_id uuid;
  v_today date := private.companion_today();
  v_day_start timestamptz;
  v_day_end timestamptz;
  v_count integer;
begin
  if v_user_id is null then raise exception 'NOT_AUTHENTICATED'; end if;

  select room_id into v_room_id
  from public.room_sessions
  where user_id = v_user_id
    and expires_at > pg_catalog.now()
    and status <> 'done'
  order by started_at desc
  limit 1;

  if v_room_id is null then raise exception 'NO_ACTIVE_ROOM'; end if;

  v_day_start := pg_catalog.timezone('Asia/Taipei', v_today::timestamp);
  v_day_end := pg_catalog.timezone('Asia/Taipei', (v_today + 1)::timestamp);

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(v_room_id::text || ':' || v_today::text, 130913)
  );

  if exists (
    select 1
    from public.room_strawberries
    where room_id = v_room_id
      and source = 'entry'
      and spawned_at >= v_day_start
      and spawned_at < v_day_end
  ) then
    return false;
  end if;

  v_count := 1 + pg_catalog.floor(pg_catalog.random() * 5)::integer;

  insert into public.room_strawberries(room_id, x_percent, y_percent, source)
  select
    v_room_id,
    8 + pg_catalog.floor(pg_catalog.random() * 81)::integer,
    12 + pg_catalog.floor(pg_catalog.random() * 71)::integer,
    'entry'
  from pg_catalog.generate_series(1, v_count);

  return true;
end;
$$;

revoke execute on function public.ensure_room_strawberries() from public, anon, authenticated;
grant execute on function public.ensure_room_strawberries() to authenticated;

-- Claim exactly one berry. Row locking makes simultaneous taps resolve to one
-- winner only.
create or replace function public.claim_room_strawberry(p_strawberry_id uuid)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_room_id uuid;
  v_berry public.room_strawberries%rowtype;
begin
  if v_user_id is null then raise exception 'NOT_AUTHENTICATED'; end if;

  select room_id into v_room_id
  from public.room_sessions
  where user_id = v_user_id
    and expires_at > pg_catalog.now()
    and status <> 'done'
  order by started_at desc
  limit 1;

  if v_room_id is null then raise exception 'NO_ACTIVE_ROOM'; end if;

  select * into v_berry
  from public.room_strawberries
  where id = p_strawberry_id
  for update;

  if not found or v_berry.room_id <> v_room_id then
    raise exception 'STRAWBERRY_NOT_IN_ROOM';
  end if;

  if v_berry.claimed_by is not null then return false; end if;

  update public.room_strawberries
  set claimed_by = v_user_id,
      claimed_at = pg_catalog.now()
  where id = p_strawberry_id;

  insert into public.strawberry_pickups(user_id, room_strawberry_id)
  values (v_user_id, p_strawberry_id)
  on conflict (room_strawberry_id) do nothing;

  return true;
end;
$$;

revoke execute on function public.claim_room_strawberry(uuid) from public, anon, authenticated;
grant execute on function public.claim_room_strawberry(uuid) to authenticated;

-- Replace the hardened completion RPC so every successful new completion also
-- drops 1-3 shared berries into that room.
create or replace function public.record_room_task_completion(p_room_session_id text)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_session public.room_sessions%rowtype;
  v_completion_id bigint;
  v_drop_count integer;
begin
  if v_user_id is null then raise exception 'NOT_AUTHENTICATED'; end if;
  if p_room_session_id is null or pg_catalog.length(p_room_session_id) = 0 then
    raise exception 'INVALID_ROOM_SESSION';
  end if;

  select * into v_session
  from public.room_sessions
  where id = p_room_session_id
    and user_id = v_user_id
    and expires_at > pg_catalog.now()
  for update;

  if not found then raise exception 'INVALID_ROOM_SESSION'; end if;
  if v_session.room_id is null then raise exception 'INVALID_ROOM_SESSION'; end if;
  if v_session.started_at > pg_catalog.now() - interval '30 seconds' then
    raise exception 'ROOM_COMPLETION_TOO_EARLY';
  end if;

  insert into public.task_completions(user_id, task, room_session_id)
  values (v_user_id, v_session.task, v_session.id)
  on conflict do nothing
  returning id into v_completion_id;

  if v_completion_id is not null then
    insert into public.room_completion_events(room_id, user_id, name, animal, task)
    values (
      v_session.room_id::text,
      v_user_id,
      v_session.name,
      v_session.animal,
      v_session.task
    );

    v_drop_count := 1 + pg_catalog.floor(pg_catalog.random() * 3)::integer;
    insert into public.room_strawberries(room_id, x_percent, y_percent, source)
    select
      v_session.room_id,
      8 + pg_catalog.floor(pg_catalog.random() * 81)::integer,
      12 + pg_catalog.floor(pg_catalog.random() * 71)::integer,
      'completion'
    from pg_catalog.generate_series(1, v_drop_count);
  end if;

  update public.room_sessions
  set status = 'done',
      help_request_id = null,
      last_seen = pg_catalog.now()
  where id = v_session.id
    and user_id = v_user_id;

  return v_completion_id is not null;
end;
$$;

revoke execute on function public.record_room_task_completion(text) from public, anon, authenticated;
grant execute on function public.record_room_task_completion(text) to authenticated;

-- Make realtime INSERT/UPDATE events available for the shared berries.
do $$
begin
  alter publication supabase_realtime add table public.room_strawberries;
exception
  when duplicate_object then null;
end;
$$;

commit;
